<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[Hi]]>
    </line>
    <line>
      <![CDATA[Hii2]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="179" started-at="2020-07-29T06:08:43Z" finished-at="2020-07-29T06:08:43Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="179" started-at="2020-07-29T06:08:43Z" finished-at="2020-07-29T06:08:43Z">
      <class name="Org.qsp.testngdemo.DemoList">
        <test-method status="PASS" signature="m1()[pri:0, instance:Org.qsp.testngdemo.DemoList@68be2bc2]" name="m1" duration-ms="37" started-at="2020-07-29T06:08:43Z" finished-at="2020-07-29T06:08:43Z">
          <reporter-output>
            <line>
              <![CDATA[Hi]]>
            </line>
          </reporter-output>
        </test-method> <!-- m1 -->
        <test-method status="FAIL" signature="m2()[pri:0, instance:Org.qsp.testngdemo.DemoList@68be2bc2]" name="m2" duration-ms="12" started-at="2020-07-29T06:08:43Z" finished-at="2020-07-29T06:08:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at Org.qsp.testngdemo.DemoList.m2(DemoList.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Hii2]]>
            </line>
          </reporter-output>
        </test-method> <!-- m2 -->
      </class> <!-- Org.qsp.testngdemo.DemoList -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
